version: "2"
services:
  go:
    build: .
    restart: always
    environment:
      DB_HOST: db:3306
      DB_PASSWORD: password
    ports:
      - "8000:80"
    volumes:
      - ./go/src/:/go/src/app
    depends_on:
      - db
  db:
    image: mysql:5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: go
      MYSQL_USER: go
      MYSQL_PASSWORD: password
